api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/config/api_platform/resource'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]